import json
import os
from datetime import datetime
from math import gcd

import numpy as np
from scipy import signal
from scipy.io import wavfile

from utils.dataloading.waterflow_preprocessing import (
    build_experiment_context,
    get_sorted_wav_files,
    highpass_filter,
    save_spectrogram_chunks_with_snr,
)


# Corrected production dataset (2026-08-17)
#
# Important design rules:
# - one global reference RMS is shared by every source WAV and experiment;
# - each selected water-flow chunk is normalized to the requested target power;
# - the same noise chunk is paired across sources and reference-SNR levels;
# - source-WAV provenance is retained for grouped validation;
# - old relative_source_rms datasets are never generated by this entry point.
SAVE_DATE = 20260817
DATASET_VERSION = "fixed_global_rms_paired"
RANDOM_SEED = 42

MAX_FREQ_HZ = [3000, 22050]
CHUNK_SECONDS_LIST = [1]
REFERENCE_SNR_DB = [None, 0, -4, -8, -12, -16, -20]

AUDIO_SAMPLES_USED = 2646000
SAVE_NPY = True
SAVE_SPECTROGRAM_PNG = False
PNG_WITH_AXES = False

# A real 500 Hz high-pass specification.  The previous 1e-5/1e-4 dB values
# produced an effective cutoff near 170 Hz despite fp=500.
FILTER_PASS_HZ = 500
FILTER_STOP_HZ = 400
FILTER_PASS_LOSS_DB = 1
FILTER_STOP_ATTENUATION_DB = 40
STFT_FRAME_COUNT = 672

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_EXPERIMENT_DIR = os.path.join(
    REPO_ROOT,
    "Pool_boiling",
    "Subcooling_20_degrees",
    "0.3",
)
EXPERIMENT_NAMES = [
    "2025.06.18_0.3_3",
    "2025.07.09_0.3_1",
    "2025.06.11_0.3_2",
]
RECORDING_DIR_NAME = "録音データ_熱流束"
WATERFLOW_PATH = os.path.join(
    REPO_ROOT, "water_flow", "water_flow_125.wav"
)

DATASET_VARIANTS = [
    {
        "dataset_version": DATASET_VERSION,
        "output_signal_mode": "mixture",
        "snr_levels": REFERENCE_SNR_DB,
        "max_chunks_per_source": None,
    },
    {
        # Small mandatory negative control.  If this predicts heat flux under
        # grouped validation, the new dataset must not be used for claims.
        "dataset_version": DATASET_VERSION + "_noise_only_control",
        "output_signal_mode": "noise_only",
        "snr_levels": [-20],
        "max_chunks_per_source": 5,
    },
]

PREPROCESS_CONFIG = {
    "fp": FILTER_PASS_HZ,
    "fs": FILTER_STOP_HZ,
    "gpass": FILTER_PASS_LOSS_DB,
    "gstop": FILTER_STOP_ATTENUATION_DB,
    "sample_number": STFT_FRAME_COUNT,
    "audio_samples_used": AUDIO_SAMPLES_USED,
    "save_npy": SAVE_NPY,
    "save_spectrogram_png": SAVE_SPECTROGRAM_PNG,
    "png_with_axes": PNG_WITH_AXES,
    "noise_scaling_mode": "fixed_global_rms",
    "randomize_noise_offset_per_chunk": True,
    "pair_noise_across_snr": True,
    "noise_seed_scope": "shared_across_sources",
    "noise_level_folder_prefix": "reference_SNR",
    "noise_level_definition": (
        "reference level relative to one global median filtered-source RMS; "
        "not the realized SNR of each individual source chunk"
    ),
    "random_seed": RANDOM_SEED,
    "include_source_in_filename": True,
    "saved_array_dtype": "float32",
    "audio_loading": "scipy.io.wavfile + scipy.signal.resample_poly",
}


def _pcm_to_float(data):
    """Convert scipy WAV data to a librosa-like floating representation."""
    data = np.asarray(data)
    if np.issubdtype(data.dtype, np.floating):
        return data.astype(np.float64, copy=False)
    if data.dtype == np.uint8:
        return (data.astype(np.float64) - 128.0) / 128.0
    info = np.iinfo(data.dtype)
    scale = float(max(abs(info.min), info.max))
    return data.astype(np.float64) / scale


def _load_resampled_wav(path, target_sr=44100, first_channel=False):
    """Load one WAV deterministically and resample it when required."""
    source_sr, data = wavfile.read(path, mmap=True)
    data = _pcm_to_float(data)
    if data.ndim > 1:
        data = data[:, 0] if first_channel else data.mean(axis=1)
    if int(source_sr) != int(target_sr):
        divisor = gcd(int(source_sr), int(target_sr))
        data = signal.resample_poly(
            data,
            int(target_sr) // divisor,
            int(source_sr) // divisor,
        )
    return np.asarray(data, dtype=float), int(target_sr)


def _load_and_filter(path, first_channel=False):
    data, samplerate = _load_resampled_wav(
        path, first_channel=first_channel
    )
    return highpass_filter(
        data[:AUDIO_SAMPLES_USED],
        samplerate,
        FILTER_PASS_HZ,
        FILTER_STOP_HZ,
        FILTER_PASS_LOSS_DB,
        FILTER_STOP_ATTENUATION_DB,
    )


def _build_source_plans(chunk_seconds):
    plans = []
    for experiment_name in EXPERIMENT_NAMES:
        context = build_experiment_context(
            experiment_name=experiment_name,
            base_experiment_dir=BASE_EXPERIMENT_DIR,
            recording_dir_name=RECORDING_DIR_NAME,
            waterflow_path=WATERFLOW_PATH,
            save_date=SAVE_DATE,
            dataset_version=DATASET_VERSION,
            chunk_seconds=chunk_seconds,
            script_path=__file__,
        )
        folder_path = context["folder_path"]
        if not os.path.isdir(folder_path):
            raise FileNotFoundError(
                f"recording folder not found: {folder_path}"
            )
        wav_files = get_sorted_wav_files(folder_path)
        wav_paths = [os.path.join(folder_path, name) for name in wav_files]
        plans.append(
            {
                "experiment_name": experiment_name,
                "context": context,
                "wav_files": wav_files,
                "wav_paths": wav_paths,
            }
        )
    return plans


def _estimate_global_reference_rms(source_paths):
    """Return one scalar derived once from all configured source WAVs."""
    rms_by_path = {}
    for index, path in enumerate(source_paths, start=1):
        filtered = _load_and_filter(path)
        rms_by_path[path] = float(np.sqrt(np.mean(filtered**2)))
        print(
            f"reference RMS {index}/{len(source_paths)}: "
            f"{os.path.basename(path)}"
        )
    if not rms_by_path:
        raise ValueError("No source WAVs were found for global RMS estimation.")
    return float(np.median(list(rms_by_path.values()))), rms_by_path


def _write_reference_manifest(context, reference_rms, rms_by_path):
    os.makedirs(context["base_npy_save_folder_path"], exist_ok=True)
    manifest = {
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "dataset_version": context["dataset_version"],
        "reference_rms": reference_rms,
        "reference_scope": "all configured source WAVs across three experiments",
        "source_count": len(rms_by_path),
        "label_or_individual_source_used_for_noise_level": False,
        "calibrated_spl": False,
        "filter": {
            "pass_hz": FILTER_PASS_HZ,
            "stop_hz": FILTER_STOP_HZ,
            "pass_loss_db": FILTER_PASS_LOSS_DB,
            "stop_attenuation_db": FILTER_STOP_ATTENUATION_DB,
        },
        "source_rms": [
            {
                "path": os.path.relpath(path, REPO_ROOT),
                "filtered_rms": rms,
            }
            for path, rms in sorted(rms_by_path.items())
        ],
    }
    path = os.path.join(
        context["base_npy_save_folder_path"],
        "global_reference_manifest.json",
    )
    with open(path, "w", encoding="utf-8") as file:
        json.dump(manifest, file, ensure_ascii=False, indent=2)


def run_all_experiments():
    if not os.path.isfile(WATERFLOW_PATH):
        raise FileNotFoundError(f"water-flow WAV not found: {WATERFLOW_PATH}")

    print("Preloading and filtering the shared water-flow recording...")
    filtered_waterflow_noise = _load_and_filter(
        WATERFLOW_PATH, first_channel=True
    )

    for chunk_i, chunk_seconds in enumerate(CHUNK_SECONDS_LIST, start=1):
        print(
            f"========== chunk {chunk_i}/{len(CHUNK_SECONDS_LIST)}: "
            f"{chunk_seconds:g}s =========="
        )
        plans = _build_source_plans(chunk_seconds)
        all_source_paths = [
            path for plan in plans for path in plan["wav_paths"]
        ]
        print(
            "Estimating one global filtered-source RMS from "
            f"{len(all_source_paths)} WAVs..."
        )
        global_reference_rms, rms_by_path = _estimate_global_reference_rms(
            all_source_paths
        )
        reference_provenance = (
            f"median filtered RMS of {len(all_source_paths)} source WAVs "
            "across all configured experiments; one scalar shared by every "
            "sample; not calibrated SPL"
        )
        print(f"global_reference_rms={global_reference_rms:.10g}")

        for exp_i, plan in enumerate(plans, start=1):
            experiment_name = plan["experiment_name"]
            wav_files = plan["wav_files"]
            wav_paths = plan["wav_paths"]
            discovery_context = plan["context"]
            label_count = len(
                discovery_context["heat_flux_label_by_index"]
            )
            if label_count and label_count != len(wav_files):
                print(
                    f"Warning: heat flux labels={label_count}, "
                    f"wav files={len(wav_files)} in {experiment_name}"
                )

            print(
                f"========== experiment {exp_i}/{len(plans)}: "
                f"{experiment_name} | wav={len(wav_files)} =========="
            )
            print("Preloading and filtering source WAVs...")
            filtered_signal_by_path = {
                path: _load_and_filter(path) for path in wav_paths
            }

            for variant_i, variant in enumerate(DATASET_VARIANTS, start=1):
                context = build_experiment_context(
                    experiment_name=experiment_name,
                    base_experiment_dir=BASE_EXPERIMENT_DIR,
                    recording_dir_name=RECORDING_DIR_NAME,
                    waterflow_path=WATERFLOW_PATH,
                    save_date=SAVE_DATE,
                    dataset_version=variant["dataset_version"],
                    chunk_seconds=chunk_seconds,
                    script_path=__file__,
                )
                variant_config = {
                    **PREPROCESS_CONFIG,
                    **variant,
                    "fixed_reference_signal_rms": global_reference_rms,
                    "fixed_reference_provenance": reference_provenance,
                }
                _write_reference_manifest(
                    context, global_reference_rms, rms_by_path
                )

                print(
                    f"----- variant {variant_i}/{len(DATASET_VARIANTS)}: "
                    f"{variant['dataset_version']} -----"
                )
                for max_freq_hz in MAX_FREQ_HZ:
                    print(f"----- max_freq_hz={max_freq_hz} -----")
                    for wav_i, (filename, file_path) in enumerate(
                        zip(wav_files, wav_paths), start=1
                    ):
                        save_spectrogram_chunks_with_snr(
                            file_path=file_path,
                            max_freq_hz=max_freq_hz,
                            chunk_seconds=chunk_seconds,
                            context=context,
                            config=variant_config,
                            snr_db=variant["snr_levels"],
                            prefiltered_signal=filtered_signal_by_path[
                                file_path
                            ],
                            prefiltered_waterflow_noise=(
                                filtered_waterflow_noise
                            ),
                        )
                        print(
                            f"---------- {wav_i} / {len(wav_files)} "
                            f"({filename}) done! ----------"
                        )

            del filtered_signal_by_path

    print("---------- All experiments done! ----------")


if __name__ == "__main__":
    run_all_experiments()
